---
- name: Create Base Path
  shell:
    cmd: |
      mkdir {{install_path}}/redis_{{master_port}}/{conf,data,run,logs} -p
      mkdir {{install_path}}/redis_{{slave_port}}/{conf,data,run,logs} -p

- name: Check if redis exists
  shell: 'ps -ef | grep redis-server | grep -v "grep" | wc -l'
  register: check_redis

- name: Stop redis server
  shell: 'redis-cli -h {{ ansible_facts.ens192.ipv4.address }} -p {{item.port}}  shutdown'
  with_items:
    - { port: '{{master_port}}' }
    - { port: '{{slave_port}}' }
  when: check_redis.stdout|int > 0

- name: Delete Aof
  shell: 'rm -rf {{install_path}}/redis_{{item.port}}/data/appendonly.aof'
  with_items:
    - { port: '{{master_port}}' }
    - { port: '{{slave_port}}' }

- name: Delete nodes.conf
  shell: 'rm -rf {{install_path}}/redis_{{item.port}}/conf/nodes.conf'
  with_items:
    - { port: '{{master_port}}' }
    - { port: '{{slave_port}}' }

- name: Unpack redis tar
  unarchive:
    src: '{{file_name}}.tar.gz'
    dest: '/opt'
  tags: test

- name: install depends
  yum: 
    name: "{{ item }}"
    state: installed
  loop:
    - gcc
    - gcc-c++
    - make
  tags: install  

- name: Installing Redis
  shell: make && make install
  args:
    chdir: '/opt/{{file_name}}'
  tags: install

- name: Replace common config
  template:
    src: "{{ item.conf }}"
    dest: /opt/redis-cluster/redis_{{item.port}}/conf/redis.conf
  with_items:
    - { conf: 'redis_6379.conf.j2', port: '{{master_port}}' }
    - { conf: 'redis_6380.conf.j2', port: '{{slave_port}}' }

- name: copy redis-cli
  shell: cp /opt/{{file_name}}/src/redis-cli /usr/bin/

- name: Start redis
  shell: '/opt/{{file_name}}/src/redis-server {{install_path}}/redis_{{item.port}}/conf/redis.conf'
  become:  true
  with_items:
    - { port: '{{master_port}}' }
    - { port: '{{slave_port}}' }
  tags: up


- name: Create Cluster
  shell: 'echo yes | redis-cli --cluster create 10.1.3.100:6379 10.1.3.101:6379 10.1.3.102:6379 10.1.3.100:6380 10.1.3.101:6380 10.1.3.102:6380 --cluster-replicas 1'
  run_once: true
  tags: up
