---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: harbor-data
  namespace: harbor
spec:
  capacity:
    storage: 1Ti
  cephfs:
    monitors:
      - '10.1.9.51:6789'
      - '10.1.9.52:6789'
      - '10.1.9.53:6789'
    path: /harbor/data
    user: admin
    secretRef:
      name: ceph-secret
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: harbor-data
  namespace: harbor
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Ti
  storageClassName: ''
  volumeMode: Filesystem
