kind: PersistentVolume
apiVersion: v1
metadata:
  namespace: cicd
  name: jenkins-pv 
spec:
  capacity:
    storage: 500Gi
  cephfs:
    monitors:
      - '10.1.9.51:6789'
      - '10.1.9.52:6789'
      - '10.1.9.53:6789'
    path: /jenkins
    user: admin
    secretRef:
      name: ceph-secret
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
