apiVersion: v1
kind: PersistentVolume
metadata:
  name: jenkins-pv-nfs
spec:
  capacity:
    storage: 500Gi
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Delete
  nfs:
    server: 10.1.9.11
    path: /data/jenkins
