kind: Deployment
apiVersion: apps/v1
metadata:
  name: nexus3
  namespace: cicd
  labels:
    app: nexus3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nexus3
  template:
    metadata:
      labels:
        app: nexus3
    spec:
      volumes:
        - name: nexus-data
          persistentVolumeClaim:
            claimName: nexus-pvc
      containers:
        - name: nexus3
          image: 'sonatype/nexus3:3.37.3'
          ports:
            - name: web
              containerPort: 8081
              protocol: TCP
            - name: http-5000
              containerPort: 5000
              protocol: TCP
          resources:
            limits:
              cpu: '4'
              memory: 8048Mi
            requests:
              cpu: '4'
              memory: 8048Mi
          volumeMounts:
            - name: nexus-data
              mountPath: /nexus-data
          livenessProbe:
            httpGet:
              path: /
              port: 8081
              scheme: HTTP
            initialDelaySeconds: 1000
            timeoutSeconds: 60
            periodSeconds: 30
            successThreshold: 1
            failureThreshold: 6
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
          securityContext:
            privileged: false
            runAsUser: 0
            runAsNonRoot: false
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
