kind: PersistentVolume
apiVersion: v1
metadata:
  namespace: cicd
  name: nexus-pv 
spec:
  capacity:
    storage: 2Ti
  cephfs:
    monitors:
      - '10.1.9.51:6789'
      - '10.1.9.52:6789'
      - '10.1.9.53:6789'
    path: /nexus3/sonatype-work/nexus3
    user: admin
    secretRef:
      name: ceph-secret
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
