kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: nexus-pvc 
  namespace: cicd
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Ti
  storageClassName: ""
  volumeMode: Filesystem
